name: Prtfolio
on:
  push:
    branches: [main]
  workflow_dispatch: # push and workflow dispatch can be used together  in combination
                       # or both the options.
permissions:
    pages: write
    id-token: write
    contents: read
jobs:
   deploy:
     runs-on: ubuntu-latest
     environment:
           