name: Devsecops End-to-End
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  code-quality:
      uses: ./.github/workflows/code-quality.yml

  secret-scan:
      uses: ./.github/workflows/secrets-scan.yml

  dependency-scan:
      uses: ./.github/workflows/dependency-scan.yml

  docker-lint:
      uses: ./.github/workflows/docker-lint.yml
