name: Devsecops End-to-End
on:
  push:
    branches: [main]

jobs:
  code-quality:
      uses: ./.github/workflows/code-quality.yml

  secret-scan:
      uses: ./.github/workflows/secrets-scan.yml
      secrets: inherit

  dependency-scan:
      uses: ./.github/workflows/dependency-scan.yml

  docker-lint:
      uses: ./.github/workflows/docker-lint.yml

  
