#Uses trivy Image Scanner for CVEs (Common Vulnerabilities)
name: Image Scan
on:
  workflow_call:
    inputs:
       docker_username:
         required: true
         type: string
    secrets:
     docker_token:
       required: true


  
jobs:
  image-scanner:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
           username: ${{ inputs.docker_username }}
           password: ${{ secrets.docker_token }} 
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@0.35.1
        with:
          image-ref: ${{ inputs.docker_username }}/github-actions-app:latest
          severity: CRITICAL
          exit-code: 1
