#API Keys, sensitive data, credentials (gets committed unintentionally sometimes)
#GitLeaks, A SAST tools for detecting and preventinh hardcoded screts like passwords,API keysand tokens.

##### IMP #### for scanning the old Git history we add with: fetch-depth: 0 
name: Secrets scan

on:
  workflow_call:

jobs:
    secret-scan:
        runs-on: ubuntu-latest
        steps:
          - name: Code Checkout
            uses: actions/checkout@v4
            with:
                fetch-depth: 0

          - name: Run Gitleaks Scanner
            uses: gitleaks/gitleaks-actions@v2  #Gitleaks scanner use env variables
            env:
               GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #GitHub automatically generates a token when runs a workflow
                                                         # This token is given to runner of gitleaks

     
